// Optional demo data a user can load to see Pace populated with a realistic
// week, rather than starting from a blank slate. Triggered manually from Me
// → Settings, never run automatically on signup.

import { createDoc } from '@/firebase/firestore'
import { currentMonthKey, currentWeekKey, todayISO } from '@/utils/date'
import type { Goal, Habit, Project, Task, WeeklyFocus } from '@/types'

export async function seedDemoData(uid: string) {
  const placement = await createDoc(uid, 'projects', {
    name: 'Placement',
    notes: '',
    status: 'making_progress',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  } satisfies Omit<Project, 'id'>)

  const moving = await createDoc(uid, 'projects', {
    name: 'Moving Home',
    notes: '',
    status: 'just_started',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  } satisfies Omit<Project, 'id'>)

  const now = new Date().toISOString()
  const tasks: Omit<Task, 'id'>[] = [
    {
      title: 'Organize placement files',
      duration: 20,
      status: 'active',
      timing: 'flexible',
      scheduledFor: todayISO(),
      scheduledTime: null,
      dueDate: null,
      projectId: placement,
      goalId: null,
      weeklyFocusId: null,
      dependsOnTaskId: null,
      priority: 'must',
      energy: 2,
      isTop3: true,
      parentTaskId: null,
      recurrence: 'none',
      minimumVersionOf: null,
      skipCount: 0,
      skipReasons: [],
      lastSkippedAt: null,
      createdAt: now,
      completedAt: null,
      source: 'manual',
    },
    {
      title: 'Prepare project notes',
      duration: 15,
      status: 'active',
      timing: 'flexible',
      scheduledFor: todayISO(),
      scheduledTime: null,
      dueDate: null,
      projectId: placement,
      goalId: null,
      weeklyFocusId: null,
      dependsOnTaskId: null,
      priority: 'should',
      energy: 2,
      isTop3: false,
      parentTaskId: null,
      recurrence: 'none',
      minimumVersionOf: null,
      skipCount: 0,
      skipReasons: [],
      lastSkippedAt: null,
      createdAt: now,
      completedAt: null,
      source: 'manual',
    },
    {
      title: 'Pack one kitchen cabinet',
      duration: 15,
      status: 'active',
      timing: 'flexible',
      scheduledFor: todayISO(),
      scheduledTime: null,
      dueDate: null,
      projectId: moving,
      goalId: null,
      weeklyFocusId: null,
      dependsOnTaskId: null,
      priority: 'should',
      energy: 1,
      isTop3: true,
      parentTaskId: null,
      recurrence: 'none',
      minimumVersionOf: null,
      skipCount: 0,
      skipReasons: [],
      lastSkippedAt: null,
      createdAt: now,
      completedAt: null,
      source: 'manual',
    },
    {
      title: 'Pack desk drawer',
      duration: 10,
      status: 'active',
      timing: 'flexible',
      scheduledFor: null,
      scheduledTime: null,
      dueDate: null,
      projectId: moving,
      goalId: null,
      weeklyFocusId: null,
      dependsOnTaskId: null,
      priority: 'could',
      energy: 1,
      isTop3: false,
      parentTaskId: null,
      recurrence: 'none',
      minimumVersionOf: null,
      skipCount: 0,
      skipReasons: [],
      lastSkippedAt: null,
      createdAt: now,
      completedAt: null,
      source: 'manual',
    },
    {
      title: 'Sort documents',
      duration: 20,
      status: 'active',
      timing: 'flexible',
      scheduledFor: null,
      scheduledTime: null,
      dueDate: null,
      projectId: moving,
      goalId: null,
      weeklyFocusId: null,
      dependsOnTaskId: null,
      priority: 'could',
      energy: 2,
      isTop3: false,
      parentTaskId: null,
      recurrence: 'none',
      minimumVersionOf: null,
      skipCount: 0,
      skipReasons: [],
      lastSkippedAt: null,
      createdAt: now,
      completedAt: null,
      source: 'manual',
    },
  ]
  await Promise.all(tasks.map((t) => createDoc(uid, 'tasks', t)))

  await createDoc(uid, 'habits', {
    name: 'Movement',
    goalVersion: [
      { label: 'push-ups', value: '20 push-ups' },
      { label: 'plank', value: '30 sec plank' },
      { label: 'run', value: '5 min run' },
    ],
    minimumVersion: [
      { label: 'push-ups', value: '5 push-ups' },
      { label: 'plank', value: '10 sec plank' },
      { label: 'run', value: '2 min movement' },
    ],
    goalId: null,
    createdAt: now,
    archivedAt: null,
  } satisfies Omit<Habit, 'id'>)

  const goals: Omit<Goal, 'id'>[] = [
    {
      title: 'Stay consistent with placement',
      month: currentMonthKey(),
      timeframe: 'month',
      weekOf: null,
      startDate: null,
      endDate: null,
      status: 'making_progress',
      milestones: [],
      linkedProjectIds: [placement],
      createdAt: now,
    },
    {
      title: 'Make steady progress on moving',
      month: currentMonthKey(),
      timeframe: 'month',
      weekOf: null,
      startDate: null,
      endDate: null,
      status: 'just_started',
      milestones: [],
      linkedProjectIds: [moving],
      createdAt: now,
    },
    {
      title: 'Build a movement habit',
      month: currentMonthKey(),
      timeframe: 'month',
      weekOf: null,
      startDate: null,
      endDate: null,
      status: 'just_started',
      milestones: [],
      linkedProjectIds: [],
      createdAt: now,
    },
  ]
  await Promise.all(goals.map((g) => createDoc(uid, 'goals', g)))

  const weeklyFocus: Omit<WeeklyFocus, 'id'>[] = [
    {
      title: 'Placement',
      description: 'Complete first project task.',
      weekOf: currentWeekKey(),
      goalId: null,
      status: 'making_progress',
      createdAt: now,
    },
    {
      title: 'Moving',
      description: 'Finish packing bedroom.',
      weekOf: currentWeekKey(),
      goalId: null,
      status: 'just_started',
      createdAt: now,
    },
    {
      title: 'Health',
      description: 'Move at least 4 days.',
      weekOf: currentWeekKey(),
      goalId: null,
      status: 'just_started',
      createdAt: now,
    },
  ]
  await Promise.all(weeklyFocus.map((w) => createDoc(uid, 'weeklyFocus', w)))
}
